// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  provider: __t.string(),
  externalId: __t.string().name("external_id"),
  login: __t.string(),
  scopes: __t.string(),
  linkedAt: __t.timestamp().name("linked_at"),
  status: __t.string(),
  expiresAt: __t.option(__t.timestamp()).name("expires_at"),
});
