// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  id: __t.u64(),
  identity: __t.identity(),
  provider: __t.string(),
  externalId: __t.string(),
  login: __t.string(),
  scopes: __t.string(),
  linkedAt: __t.timestamp(),
  status: __t.string(),
  lastError: __t.string(),
});
export type Account = __Infer<typeof Account>;

export const Config = __t.object("Config", {
  key: __t.u8(),
  config: __t.string(),
  secret: __t.string(),
});
export type Config = __Infer<typeof Config>;

export const MyAccounts = __t.object("MyAccounts", {});
export type MyAccounts = __Infer<typeof MyAccounts>;

export const OauthAccountInfo = __t.object("OauthAccountInfo", {
  provider: __t.string(),
  externalId: __t.string(),
  login: __t.string(),
  scopes: __t.string(),
  linkedAt: __t.timestamp(),
  status: __t.string(),
  expiresAt: __t.option(__t.timestamp()),
});
export type OauthAccountInfo = __Infer<typeof OauthAccountInfo>;

export const RefreshJob = __t.object("RefreshJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  accountId: __t.u64(),
});
export type RefreshJob = __Infer<typeof RefreshJob>;

export const State = __t.object("State", {
  state: __t.string(),
  identity: __t.identity(),
  provider: __t.string(),
  verifier: __t.string(),
  scopes: __t.string(),
  returnTo: __t.string(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type State = __Infer<typeof State>;

export const Token = __t.object("Token", {
  accountId: __t.u64(),
  accessToken: __t.string(),
  refreshToken: __t.option(__t.string()),
  expiresAt: __t.option(__t.timestamp()),
  refreshedAt: __t.timestamp(),
  refreshingUntil: __t.option(__t.timestamp()),
  refreshFailures: __t.u32(),
});
export type Token = __Infer<typeof Token>;

