// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as DemoProfileProcedure from "../demo_profile_procedure";
import * as OauthBeginProcedure from "../oauth_begin_procedure";
import * as OauthCompleteProcedure from "../oauth_complete_procedure";
import * as OauthUnlinkProcedure from "../oauth_unlink_procedure";

export type DemoProfileArgs = __Infer<typeof DemoProfileProcedure.params>;
export type DemoProfileResult = __Infer<typeof DemoProfileProcedure.returnType>;
export type OauthBeginArgs = __Infer<typeof OauthBeginProcedure.params>;
export type OauthBeginResult = __Infer<typeof OauthBeginProcedure.returnType>;
export type OauthCompleteArgs = __Infer<typeof OauthCompleteProcedure.params>;
export type OauthCompleteResult = __Infer<typeof OauthCompleteProcedure.returnType>;
export type OauthUnlinkArgs = __Infer<typeof OauthUnlinkProcedure.params>;
export type OauthUnlinkResult = __Infer<typeof OauthUnlinkProcedure.returnType>;

