// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as DemoProfileProcedure from "../demo_profile_procedure";

export type DemoProfileArgs = __Infer<typeof DemoProfileProcedure.params>;
export type DemoProfileResult = __Infer<typeof DemoProfileProcedure.returnType>;

