// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const OauthAccount = __t.object("OauthAccount", {
  id: __t.u64(),
  identity: __t.identity(),
  provider: __t.string(),
  externalId: __t.string(),
  login: __t.string(),
  scopes: __t.string(),
  linkedAt: __t.timestamp(),
  status: __t.string(),
  lastError: __t.string(),
});
export type OauthAccount = __Infer<typeof OauthAccount>;

export const OauthAccountInfo = __t.object("OauthAccountInfo", {
  provider: __t.string(),
  externalId: __t.string(),
  login: __t.string(),
  scopes: __t.string(),
  linkedAt: __t.timestamp(),
  status: __t.string(),
  expiresAt: __t.option(__t.timestamp()),
});
export type OauthAccountInfo = __Infer<typeof OauthAccountInfo>;

export const OauthRefreshJob = __t.object("OauthRefreshJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  accountId: __t.u64(),
});
export type OauthRefreshJob = __Infer<typeof OauthRefreshJob>;

export const OauthState = __t.object("OauthState", {
  state: __t.string(),
  identity: __t.identity(),
  provider: __t.string(),
  verifier: __t.string(),
  scopes: __t.string(),
  returnTo: __t.string(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type OauthState = __Infer<typeof OauthState>;

export const OauthToken = __t.object("OauthToken", {
  accountId: __t.u64(),
  accessToken: __t.string(),
  refreshToken: __t.option(__t.string()),
  expiresAt: __t.option(__t.timestamp()),
  refreshedAt: __t.timestamp(),
  refreshingUntil: __t.option(__t.timestamp()),
  refreshFailures: __t.u32(),
});
export type OauthToken = __Infer<typeof OauthToken>;

